language: node_js
node_js:
- '10'

deploy:
  provider: heroku
  api_key: "q9w3aeAXppUUInbDkW6A3GvCAVPYLrZwlwcm4FfqGnd4H0rhiXj6jKRiCI9lVvIadY4JGkWjEnwLqANUy7NRuUsQCQWSHWxImjyhukSS8fD3ELg5TYXS54ajdpQ9wziXYsfJ6WdLKekZS01r+wuxgZlPw0RK/EgjOndcCLWst11EFqDaAlF017ffEceXwptVb3X/IUy/7Sf4skxiDqvRvBZg7PLXDc9LkgX//eLKNf2gXrhNtavM13vSIF5KcxN9YTASbhHQmLovWj/vuvBqnm4F5HsKw2iSJ0517FOoTjOWV/wsVUOSl/HOT1E2Yt6ZQeD1QfFC/l0Kbmrm4hLQwi8ofCmg79TjaM9GwGCLQLwSzWZ9A1/wiGGXp6F1d3q69P85lXMGEjoQHPEekJ5CSaezVh+Ls2wZBzdlEwROkqWSBRpRo6/bHIvOeE9nNiOTraCDB0cl3kSuiiK3hlL3F6AdYvNxq2E5mP00jSTX2DGSXZbtF3ArJGRrhAKsxZzvnYmUo1bBgThwEjeUHY+m/qQiSQKtjxKbbh2SAZt84YL5tRs78FlHBwOShcGnW9FL94p38N6eQDQGZUYH2I2+MDSIC0l/z1nDaQdJRiobLfM2FuMseZLHzO7SDwfwB16/ETig7HRzwbmTn5hu+Z7bU4KvLZTDyPXuZK9iLzeCMd8="
  app: task-manager-warsawjs
